config/routes.rb
Fiso5as::Application.routes.draw do
  resources :matches, only: %i( index show new create )
  resources :game_weeks, only: %i( index )
  get '/admin' => 'game_weeks#index'

  namespace :fiveaside do
    get '/:season/:game_week/:fixture' => 'matches#show'
    get '/:access_token' => 'matches#index', as: :gw
  end

  root to: "landing_page#index"
end

app/models/game_week.rb
class GameWeek < ApplicationRecord
  DEADLINE_PADDING = 30.minutes
  ACTIVATION_HOURS = 24

  has_many :matches, -> { order(:gw_fixture_no) }, dependent: :destroy

  validates_presence_of :season, :gw_no, :access_token, :deadline_at
  validates_uniqueness_of :access_token
  validates_uniqueness_of :gw_no, scope: :season

  before_validation :generate_access_token, on: :create
  before_validation :set_deadline, on: :create

  def self.active
    where(finished: false).where('deadline_at < ?', Time.zone.now + ACTIVATION_HOURS.hours)
  end

  def self.sync_open
    #RailsExceptionHandler.catch do
      raise "Something is wrong. Found #{active.count} active gameweeks" if active.count > 2
      active.each do |game_week|
        game_week.set_up unless game_week.id == 60
        game_week.fpl_sync if game_week.ongoing?
      end
    #end
  end

  def self.update_deadlines
    RailsExceptionHandler.catch do
      where(finished: false).each do |gw|
        gw.send(:set_deadline, force: true)
        gw.save!
      end
    end
  end

  def ongoing?
    !finished && (deadline_at + DEADLINE_PADDING) < Time.zone.now
  end

  def name
    "Game week #{gw_no}"
  end

  def set_up
    matches.each do |match|
      match.set_up_match!(skip_fpl_sync: true) if match.h2h_matches.count == 0
    end
  end

  def fpl_sync
    FplScraper.clear_cache
    time = Time.zone.now
    ActiveRecord::Base.transaction do
      matches.each(&:fpl_sync)
    end
    set_finished
    self.last_sync_took = Time.zone.now - time
    self.save
  end

  def setup
    matches.each do |match|
      match.set_up_match!(skip_fpl_sync: true)
    end
  end

  private

  def generate_access_token
    self.access_token ||= (0...8).map{ ('A'..'Z').to_a[rand(26)] }.join
  end

  def set_deadline(force: false)
    return if deadline_at.present? && !force
    fpl_timestamp = fpl_data['deadline_time']
    self.deadline_at = Time.zone.parse(fpl_timestamp)
  end

  def set_finished
    self.finished = fpl_data['finished'] && fpl_data['data_checked']
    self.save!
  end

  def fpl_data
    FplScraper.static_data['events'].find{|x| x['name'] == "Gameweek #{gw_no}"}
  end
end

app/controllers/game_weeks_controller.rb
class GameWeeksController < ApplicationController
  http_basic_authenticate_with name: "admin", password: ENV['http_basic_pw']

  def index
    @seasons = GameWeek.pluck(:season).uniq.sort
    @season = params[:season] || @seasons.last
    @game_weeks = GameWeek.where(season: @season).order(:gw_no).includes(matches: [:home_team, :away_team, :game_week])
  end
end

app/views/game_weeks/index.html.haml
#game_weeks
  %h2 Game week links #{@season}
  - @seasons.each do |season|
    = link_to_unless season == @season, season, game_weeks_path(season: season)

  - @game_weeks.each do |game_week|
    %p
      %b
        = game_week.name
        &nbsp;
        &nbsp;
        %span.weak
          id:#{game_week.id}
          - if game_week.ongoing?
            ongoing
          - elsif game_week.finished?
            finished
          - else
            starts
            = l game_week.deadline_at, format: '%d %b %H:%M'
          - if game_week.last_sync_took
            \- last sync took #{game_week.last_sync_took}s
      %br/
      %span.match-name All scoreboards:
      = link_to fiveaside_gw_url(game_week.access_token), fiveaside_gw_url(game_week.access_token)
      %br/
      - game_week.matches.each do |match|
        = match.id
        %span.match-name= match.name
        = link_to friendly_match_url(match), friendly_match_url(match)
        %br/